"""Pydantic models describing the API contract (see agent/DOCUMENTATION.md §5)."""

from app.models.stocks import (
    AiAnalysisResponse,
    AiSignalAssessment,
    CandleBar,
    CompanyFundamentalsResponse,
    FinancialMetrics,
    GpwCompany,
    HeatmapItem,
    HeatmapResponse,
    QuarterlyReport,
    RatingHistoryResponse,
    RatingPoint,
    RefreshStatusResponse,
    SignalEffectiveness,
    StockHistoryResponse,
    StockRankingItem,
    StockSignalsResponse,
    StooqDailyQuote,
    TrustScoreEvent,
    TrustScoreResponse,
    VolumeSurgeItem,
    VolumeSurgeResponse,
    VsaSettings,
    VsaSignalResponse,
    VsaSignalSettings,
)

__all__ = [
    "AiAnalysisResponse",
    "AiSignalAssessment",
    "CandleBar",
    "CompanyFundamentalsResponse",
    "FinancialMetrics",
    "GpwCompany",
    "HeatmapItem",
    "HeatmapResponse",
    "QuarterlyReport",
    "RatingHistoryResponse",
    "RatingPoint",
    "RefreshStatusResponse",
    "SignalEffectiveness",
    "StockHistoryResponse",
    "StockRankingItem",
    "StockSignalsResponse",
    "StooqDailyQuote",
    "TrustScoreEvent",
    "TrustScoreResponse",
    "VolumeSurgeItem",
    "VolumeSurgeResponse",
    "VsaSettings",
    "VsaSignalResponse",
    "VsaSignalSettings",
]
